basePath: /
definitions:
  controller.LoginReq:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  controller.RegisterReq:
    properties:
      email:
        type: string
      password:
        type: string
      phone:
        type: string
      username:
        type: string
    type: object
host: 127.0.0.1:8080
info:
  contact: {}
  description: 实现用户注册、登录接口调试
  title: 用户管理后端API
  version: "1.0"
paths:
  /user/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: 登录入参
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/controller.LoginReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: 用户登录
      tags:
      - 用户模块
  /user/register:
    post:
      consumes:
      - application/json
      parameters:
      - description: 注册入参
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/controller.RegisterReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: 用户注册
      tags:
      - 用户模块
swagger: "2.0"
